### PR TITLE
typo

### PR DESCRIPTION
**Pull request by rudeboybert**

### CODE REVIEW

**Comment by ambertin** [comment]
I just made some edits to this chapter based on Ben's comments, so if I merge this now I think it will undo those.

Would you be willing to either:
1. Merge the upstream changes and push to your repo *or*
2. Comment which sentence the typo was on so I can edit manually?

Thank you so much for your help!

**Comment by rudeboybert** [comment]
Feel free to delete this PR in that case

**Comment by rudeboybert** [comment]
Do a search for: Users who new to reproducibility and working in the project format, however, may still need reminders not to use `setwd()`.

Users who *are* new

**Comment by ambertin** [comment]
Great! Just saw that and will fix right now. Thanks for catching!

**Comment by ambertin** [comment]
Fixed typo in https://github.com/ambertin/thesis/commit/dcfe5e04422cd1cb582b5008278d72ce2e6fff64!

**Pull request closed without merging**
